/*
 ### Mistral Model ###
 Author: Jingping Yu
 RTX: joshuayu
 Created on: 2017/07/11
 */

using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Mistral.Utility.Model
{
	/// <summary>
	/// This Class handles the storage of the Meshes Generated By Mistral Trail Renderer(MTR). 
	/// </summary>
	public static class MeshManager 
	{
		#region Paths

		/// <summary>
		/// Where the Meshes are stored. 
		/// </summary>
		private const string MESH_PATH = "Assets/MTR Generated/";

		#endregion

		#region Public Interfaces

		public static void SaveMeshToResource(Mesh mesh, string fileName)
		{
			///Check if the Mesh exists
			string path = MESH_PATH + fileName + ".mtrmesh";
			if (File.Exists(path))
			{
				File.Delete(path);
				Debug.Log("The file already exists. Hence it is now overwritten. GL & HF! ");
			}

			byte[] bytes = MeshSerializer.WriteMesh(mesh, true);
			File.WriteAllBytes(path, bytes);
		}

		#endregion
	}

}
